version: '3.9'
volumes:
  mongo_data:
  pgdata:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
#     backend:
#         restart: always
#         image: node:18-alpine
#         working_dir: /app
#         environment:
#             DATABASE_URL: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongo/${MONGO_INITDB_DATABASE}?retryWrites=true&w=majority&authSource=admin
#         volumes:
#             - ./../atlas-be:/app
#             - ./../.env.backend:/app/.env
#         command: 'yarn start:dev'
#         networks:
#             atlas_development:
#     frontend:
#         restart: always
#         image: node:18-alpine
#         working_dir: /app
#         volumes:
#             - ./../client:/app
#             - ./../.env.frontend:/app/.env
#         command: 'yarn dev -p 80'
#         networks:
#             atlas_development:
#     nginx:
#         image: nginx
#         ports:
#             - '80:80'
#         volumes:
#             - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#         depends_on:
#             - backend
#             - frontend
#         networks:
#             atlas_development:
# networks:
#     atlas_development:
